# Jenkinsfile examples
sh 'docker --version'
// sh 'java --version'  
sh 'java --version' 
sh 'docker --version'
This directory contains example Jenkinsfiles written in Declarative Pipeline Syntax.mm 
